spring:
  application:
    name: event-registry

server:
  port: 8084

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html

kafka:
  bootstrap-servers: localhost:9092
  schema-registry-url: http://localhost:8081

apicurio:
  registry-url: http://localhost:8080/apis/registry/v2
  artefact-group-id: "com.demo"

logging:
  level:
    org:
      apache:
        kafka: warn
    io:
      confluent:
        kafka: warn