spring:
  application:
    name: event-reader
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      timeout: 60000
      #password: mypass

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html

server:
  port: 8082

kafka:
  bootstrap-servers: localhost:9092
  schema-registry-url: http://localhost:8081

logging:
  level:
    org:
      apache:
        kafka: warn
    io:
      confluent:
        kafka: warn

event-source:
  remote:
    enabled: true
    url: http://localhost:8084