spring:
    application:
        name: event-producer
    data:
      redis:
        database: 0
        host: localhost
        port: 6379
        timeout: 60000
        #password: mypass
kafka:
    bootstrap-servers: localhost:9092
    schema-registry-url: http://localhost:8081