logging:
  level:
    root: DEBUG

spring:
  application:
    name: event-backpressure-dispatcher

server:
  port: 8083

redis:
  # manual configuration due to pooling
  database: 0
  host: localhost
  port: 16379
  password: mypass
  timeout: 60000
  pooling:
    min-idle: 10
    max-idle: 100
    max-total: 100